site_name: Solutions Gallery
site_description: Curated C++ DSA solutions with explanations and categories
repo_url: https://github.com/Syntax-Unknown/DSA-eureka
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Arrays:
      - Two Sum: Arrays/two_sum.md
      - Subarray Sum: Arrays/subarray_sum.md

