name: Build and Deploy Solutions Gallery

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Generate Markdown
        run: python scripts/cpp_to_md.py

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   # works if repo is public
          publish_dir: ./site
